package com.engreader.app.source

import android.content.Context
import com.engreader.app.model.FeedItem
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import org.json.JSONObject

/** A bundled passage with the Chinese translation generated for it at build time. */
data class SeedPassage(
    val item: FeedItem,
    val extracted: ArticleExtractor.Extracted,
    /** One entry per paragraph, or empty when the pack carries no translation. */
    val translation: List<String>,
)

/**
 * Reads the bundled offline reading pack (`assets/seed_articles.json`).
 *
 * The pack is generated by `tools/build_seed.py` from public-domain Project
 * Gutenberg texts, and its translations by `tools/build_translations.py`, so the app
 * has graded passages to read with no network and on first launch.
 */
class SeedLibrary(private val context: Context) {

    suspend fun load(): List<SeedPassage> = withContext(Dispatchers.IO) {
        val json = try {
            context.assets.open(ASSET).use { it.readBytes().toString(Charsets.UTF_8) }
        } catch (_: Exception) {
            return@withContext emptyList()
        }
        val array = try {
            JSONObject(json).optJSONArray("articles") ?: return@withContext emptyList()
        } catch (_: Exception) {
            return@withContext emptyList()
        }
        // Parsed per entry: one malformed passage should cost that passage, not the
        // whole offline pack. `getString` throws on a missing key, and letting that
        // escape the loop discarded every other article along with it.
        buildList {
            for (i in 0 until array.length()) {
                runCatching { parse(array.getJSONObject(i)) }.getOrNull()?.let { add(it) }
            }
        }
    }

    private fun parse(o: JSONObject): SeedPassage? {
        val body = o.optString("body")
        val title = o.optString("title")
        val url = o.optString("url")
        if (body.isBlank() || title.isBlank() || url.isBlank()) return null
        val item = FeedItem(
            sourceId = o.optString("sourceId", SOURCE_ID),
            sourceName = o.optString("author", "公版文本"),
            title = title,
            summary = o.optString("subtitle", ""),
            url = url,
            publishedAt = 0L,
        )
        return SeedPassage(
            item = item,
            extracted = ArticleExtractor.Extracted(
                title = item.title,
                author = item.sourceName,
                publishedAt = 0L,
                summary = item.summary,
                paragraphs = body.split("\n\n").filter { it.isNotBlank() },
            ),
            translation = readTranslation(o),
        )
    }

    /**
     * The pack stores translations as a list of strings, but a pack generated before
     * the translation tool ran has none; an absent key is normal, not an error.
     */
    private fun readTranslation(o: JSONObject): List<String> {
        val array = o.optJSONArray("translation") ?: return emptyList()
        return buildList { for (i in 0 until array.length()) add(array.optString(i)) }
    }

    private companion object {
        const val ASSET = "seed_articles.json"
        const val SOURCE_ID = "gutenberg"
    }
}
